{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_slb_dashboard_Qps)",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 7, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Aliyun Monitor Dashboard</span>\n</div>\n\n<div style=\"font-size: 0.8rem;\" class=\"text-center\">\n  <a href=\"https://github.com/aylei/aliyun-exporter\" style=\"margin-right:8px\" target=\"_blank\"><i class=\"fa fa-2x fa-github\"></i></a>\n  <a href=\"mailto:rayingecho@gmail.com\" style=\"margin-right:8px\" target=\"_blank\"><i class=\"fa fa-2x fa-envelope\"></i></a>\n  <span>Aylei ©</span>\n</div>"
  },
  {
   "title": "RT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(aliyun_acs_slb_dashboard_Rt)"
    }
   ]
  },
  {
   "title": "Global Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_slb_dashboard_TrafficRXNew)",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(aliyun_acs_slb_dashboard_TrafficTXNew)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "labelSelector": "alertname, summary", "target": "Query", "type": "table" }
   ]
  },
  { "title": "Overviews", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 } },
  { "title": "Details", "type": "dashlist", "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 } }
 ]
}