{
 "title": "RDS Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "threshold", "query": "0,50,60,70,80,90" }
  ]
 },
 "panels": [
  {
   "title": "Running Instance Count",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(aliyun_meta_rds_info{DBInstanceStatus=\"Running\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=~\"rds.*\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Overall Tx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_rds_dashboard_MySQL_NetworkOutNew)"
    }
   ]
  },
  {
   "title": "Overall Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_rds_dashboard_MySQL_ActiveSessions)"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg_over_time(aliyun_acs_rds_dashboard_CpuUsage[$interval]) * on (instanceId) group_left(DBInstanceDescription,DBInstanceStatus) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "avg_over_time(aliyun_acs_rds_dashboard_MemoryUsage[$interval]) * on (instanceId) group_left(DBInstanceDescription,DBInstanceStatus) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "avg_over_time(aliyun_acs_rds_dashboard_IOPSUsage[$interval]) * on (instanceId) group_left(DBInstanceDescription,DBInstanceStatus) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "avg_over_time(aliyun_acs_rds_dashboard_DiskUsage[$interval]) * on (instanceId) group_left(DBInstanceDescription,DBInstanceStatus) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "avg_over_time(aliyun_acs_rds_dashboard_ConnectionUsage[$interval]) * on (instanceId) group_left(DBInstanceDescription,DBInstanceStatus) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") >= $threshold"
    }
   ]
  }
 ]
}