{
 "title": "Redis Overview",
 "tags": [ "Redis" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "threshold", "query": "0,50,60,70,80,90" }
  ]
 },
 "panels": [
  {
   "title": "Running Instance Count",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(aliyun_meta_redis_info)" }
   ]
  },
  {
   "title": "Redis Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"redis.*\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Overall Rx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_kvstore_IntranetIn)"
    }
   ]
  },
  {
   "title": "Overall Tx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_kvstore_IntranetOut)"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg_over_time(aliyun_acs_kvstore_CpuUsage[$interval]) * on (instanceId) group_left(PrivateIp) \nlabel_replace(aliyun_meta_redis_info, \"instanceId\", \"$1\", \"UserName\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "avg_over_time(aliyun_acs_kvstore_MemoryUsage[$interval]) * on (instanceId) group_left(PrivateIp) \nlabel_replace(aliyun_meta_redis_info, \"instanceId\", \"$1\", \"UserName\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "avg_over_time(aliyun_acs_kvstore_IntranetInRatio[$interval]) * on (instanceId) group_left(PrivateIp) \nlabel_replace(aliyun_meta_redis_info, \"instanceId\", \"$1\", \"UserName\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "avg_over_time(aliyun_acs_kvstore_IntranetOutRatio[$interval]) * on (instanceId) group_left(PrivateIp) \nlabel_replace(aliyun_meta_redis_info, \"instanceId\", \"$1\", \"UserName\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "avg_over_time(aliyun_acs_kvstore_ConnectionUsage[$interval]) * on (instanceId) group_left(PrivateIp) \nlabel_replace(aliyun_meta_redis_info, \"instanceId\", \"$1\", \"UserName\", \"(.*)\") >= $threshold"
    }
   ]
  }
 ]
}